version: "3.8"

services:
  luminaire-detection:
    image: luminaire-detection:latest
    container_name: luminaire-detection
    runtime: nvidia
    
    # GPU configuration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, compute, utility]
    
    # Port mapping
    ports:
      - "7860:7860"
    
    # Environment variables
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - HF_HOME=/app/.cache/huggingface
      - TRANSFORMERS_CACHE=/app/.cache/huggingface
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - LD_LIBRARY_PATH=/usr/local/lib/python3.8/dist-packages/opencv_python_headless.libs
    
    # Volume mounts
    volumes:
      - ./models:/app/models
      - ./results:/app/results
      - ./cache:/app/.cache
    
    # Device mapping (cameras)
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    
    # Add to video group and privileged mode for camera access
    group_add:
      - video
    privileged: true
    
    # Network mode
    network_mode: bridge
    
    # Restart policy
    restart: unless-stopped
    
    # Command
    command: python3 gradio_app_jetson.py
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
